### ISSUE TITLE
Arbitrum Foundation Grant

### ISSUE THREAD

**Issue by amanwithwings** [metagov/daostar#184]
Commencement date: December 5 

**Milestone #1**:  [due March 5, '24] A minimum of 3 DAOs on Arbitrum achieve EIP-4824 compliance by publishing a daoURI. 
**Milestone #2**:  [due June 5, '24] Development and deployment of the Regulatory Interface. 
**Milestone #3**:  [due September 5, '24] Release of the tax standard V1.0. 

_"Milestone #1: First round of EIP-4824 adoption drive through Arbitrum
The milestone involves driving the adoption of EIP-4824 among DAOs in the
Arbitrum ecosystem. DAOstar is currently in the initial stages of this drive,
reaching out to DAOs and providing them with the necessary resources and
support to adopt EIP-4824.
KPIs: a minimum of 3 DAOs on Arbitrum achieve EIP-4824 compliance by
publishing a daoURI.
How to track KPIs: The Foundation will measure progress by tracking the
number of DAOs that have successfully adopted EIP-4824 and published a
daoURI. This information will be picked up by a subgraph that listens to
events from a RegistrationFactory contract that the Grant Recipient will
deploy on Arbitrum.

Milestone #2: Implementation of the Regulatory Interface
This milestone involves the development and deployment of the Regulatory
Interface. The Grant Recipient has already developed a prototype of the
interface, which can be viewed here:
https://develop.d61skfzwobmxx.amplifyapp.com/ (Lab tab here)
KPIs: successful deployment of the interface, the number of DAOs writing
information to it, and the number of regulators, policymakers, and legal teams
leveraging it.
How to track KPIs: The Grant Recipient should provide the Foundation with
the feedback gathered from users to ensure the interface is meeting its
intended purpose and is user-friendly.

Milestone #3: Authoring of the DAO tax standard
This milestone involves the creation of a comprehensive tax standard for
DAOs. The Grant Recipient is in the early stages of this task, conducting
research and gathering input from various stakeholders.
KPIs: the successful release of the tax standard V1.0.

How to track KPIs: The Grant Recipient should provide the Foundation with
the feedback gathered from stakeholders to ensure it meets the needs of DAOs
and complies with existing tax regulations. The Foundation will also measure
the number of DAOs that adopt the framework."_

_"Milestone #1 - within three (3) months from the Effective Date of the

Agreement;
Milestone #2 - within six (6) months from the Effective Date of the
Agreement;
Milestone #3 - within nine (9) months from the Effective Date of the
Agreement."_

**Comment by amanwithwings** [comment]
DAOs on Arbitrum (Sourced from https://portal.arbitrum.io/projects/defi?chains=arbitrum-one_arbitrum-nova): 

1. Badger DAO
2. Balancer
3. Curve
4. Swapr
5. Kromatika Finance
6. Uniswap
7. 1inch
8. Beefy Finance
9. Galxe
10. B Protocol
11. Compound
12. dForce
13. Impermax Finance
14. Lodestar Finance
15. Notional Finance
16. Silo
17. DeFrag DAO 
18. OOKI
19. Angle Protocol
20. MakerDAO
21. Frax Finance
22. Lybra Finance
23. Vesta Finance
24. Gains Network
25. GMX
26. Handle Finance
27. Mux Protocol
28. Cryptex
29. Instadapp

**Comment by amanwithwings** [comment]
We have the proposal live at Lodestar, soon at 1inch and hopefully Balancer, Gitcoin and Treasure.

**Comment by thelastjosh** [comment]
Note from discussion today: planning on a Snapshot partnership for the Snapshot X launch, but we need to ask for an extension from Arbitrum for this.

**Comment by thelastjosh** [comment]
Plan for milestone 2: we have a working prototype but still need to improve it, I'd suggest going with new minimal MVP that reflects the new standard that DOES NOT require additional technical resources, and then once we have a good MVP we can tap mendes or rashmi or others to implement.

**Comment by thelastjosh** [comment]
In discussion with Joni and @amanwithwings , we discussed the best way of resolving Milestone 2, "Development and deployment of the Regulatory Interface".

If this is fully specified, it should only take Rashmi a week to implement.

- [ ] Publish a MINIMAL VERSION of the specification, that specifies complianceURI and endorsed legal representative.
- [ ] Add a field in daoURI, probably complianceURI or regulatoryURI.
- [ ] In complianceURI, a list of attestations made somewhere, for regulatory purposes.
- [ ] That list of attestations MUST include an endorsed legal representative attestation.
- [ ] Display this information on the explore interface.
- [ ] EITHER direct people to an EAS interface to make the attestation OR integrate it ourselves into the daostar.org registration interface.

For milestone 3, the initial version of the tax standard has already been largely written as part of the DAOstar Policy Trilemma report.

**Comment by amanwithwings** [comment]
amanwithwings, [12 Jun 2024 at 6:01:26 PM (12 Jun 2024 at 6:10:16 PM)]:
...osh <> Joni <> Aman 

- Standard is 90% ready - it needs some work. Josh will do this and hand it over to Joni - she will shop it around a few regulators and collect their feedback on the regulatory interface. 

- take the registration interface that exists at labs.daostar.org (it exists here or somewhere else), and host is somewhere else. This could be similar to the EAS attestation method. 

- IDEA: have a seperate section on the website saying "regulatory interface" and have an EAS method "register as DAO legal representative". 

- Milestones 2, 3 will be complete before Sept 5 '24 but we need more time for milestone 2 - try August.

- Val (sec/ iosco) Joni has their contact. Joni also knows a few other lawyers in the US. Once the standard is done - she'll send it out to people and try to schedule calls with them.
