### ISSUE TITLE
Update milestones

### ISSUE THREAD

**Issue by thelastjosh** [metagov/daostar#188]
See https://github.com/metagov/daostar/milestones

- [x] @amanwithwings : update our milestones in github based on the new milestones here: https://github.com/metagov/daostar/discussions/183
- [x] @amanwithwings : match issues to new milestones as best as you can, ping rashmi
- [x] @Rashmi-278 : review and update, ping josh
- [x] @thelastjosh : review and update

**Comment by amanwithwings** [comment]
Done, few comments: 

- I've consolidated all community-related issues to this milestone: https://github.com/metagov/daostar/milestone/4. @unfriendlyamendment, please review.  
- Since we haven't been tracking GIL and other grants-related issues on this GitHub, it is underrepresented atm. @Eugene, please take the lead on this. 
- @thelastjosh, looks like this milestone: https://github.com/metagov/daostar/milestone/1 can be removed/merged with: https://github.com/metagov/daostar/milestone/2 as they are quite similar.   
- All front-end/ non-major technical improvements have gone to: https://github.com/metagov/daostar/milestone/3. @Rashmi-278, please review these. 
 - As a general note, everything directly related to EIP-4824 is tracked through this milestone: https://github.com/metagov/daostar/milestone/2, and there are separate milestones for the Attestations and Regulatory work.

**Comment by Rashmi-278** [comment]
#### Milestone 2
- WIP: https://github.com/metagov/daostar/issues/25 
Moving DAODAO queries to the backend, for restructuring and pagination. We should soon think about what filters we want to have and work on our API backend

#### Milestone 2.5
- https://github.com/metagov/daostar/issues/6  ,  https://github.com/metagov/daostar/issues/5 , https://github.com/metagov/daostar/issues/7,  https://github.com/metagov/daostar/issues/12, https://github.com/metagov/daostar/issues/13
This can be easily worked on but need design help from Jenny on these

- https://github.com/metagov/daostar/issues/187
Waiting for Aragon team to provide us with the details for the API

- https://github.com/metagov/daostar/issues/58
We need to separate our Internal/Developer Docs and User Onboarding Docs.
The two links that Josh mentions at the beginning are dev docs and user docs.
I can work on developer docs easily as it's from a developer perspective developers

I would need help from Josh, Aman, and anyone else who sees the bigger picture and helps new visitors understand the standards and why the EIP 4824 approach. what is our vision? how do we envision the adoption and usage of EIP 4824?

The current status of this is,
Developer docs are reasonably up to date but there's a lot of room for improvement.

Onboarding docs exist but they are dispersed and "Hidden" among links to Google Docs, notion, HackMD links

- https://github.com/metagov/daostar/issues/102
Some issues have been closed and the Google Docs are updated with comments

- https://github.com/metagov/daostar/issues/114
This has been worked but needs a review and status update

#### Milestone 3.3

- https://github.com/metagov/daostar/issues/100
I need more details to complete the next steps on my part.

- https://github.com/metagov/daostar/issues/45
Needs a status update. I think this issue was worked on and completed.

#### Milestone 4

Issues in the milestone look good to me.

**Comment by amanwithwings** [comment]
@Rashmi-278, could you share a copy of the developer docs with me?
